services:
  db:
    image: ankane/pgvector
    container_name: my_postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase